# Funding options for Flaase
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# GitHub Sponsors username
github: [MaxenceMahieux]

# Open Collective
# open_collective: flaase

# Ko-fi
# ko_fi: flaase

# Patreon
# patreon: flaase

# Buy Me a Coffee
# buy_me_a_coffee: flaase

# Custom sponsorship URLs (up to 4)
# custom:
#   - https://flaase.dev/sponsor
