//! Dockerfile templates for different application stacks.

use crate::core::app_config::Stack;

/// Generates a Dockerfile for the given stack.
pub fn generate(stack: Stack, port: u16) -> String {
    match stack {
        Stack::NextJs => generate_nextjs(port),
        Stack::NodeJs => generate_nodejs(port),
        Stack::NestJs => generate_nestjs(port),
        Stack::Laravel => generate_laravel(port),
    }
}

/// Generates a Dockerfile for Next.js applications.
fn generate_nextjs(port: u16) -> String {
    format!(
        r#"# Next.js Dockerfile
# Generated by Flaase

FROM node:20-alpine AS base

# Install dependencies only when needed
FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN \
  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
  else echo "Lockfile not found." && exit 1; \
  fi

# Rebuild the source code only when needed
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ENV NEXT_TELEMETRY_DISABLED=1

RUN \
  if [ -f yarn.lock ]; then yarn build; \
  elif [ -f package-lock.json ]; then npm run build; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm build; \
  else echo "Lockfile not found." && exit 1; \
  fi

# Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public

# Automatically leverage output traces to reduce image size
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE {port}

ENV PORT={port}
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]
"#,
        port = port
    )
}

/// Generates a Dockerfile for Node.js applications.
fn generate_nodejs(port: u16) -> String {
    format!(
        r#"# Node.js Dockerfile
# Generated by Flaase

FROM node:20-alpine AS builder

WORKDIR /app

# Install dependencies
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN \
  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
  else npm install; \
  fi

# Copy source
COPY . .

# Build if there's a build script
RUN npm run build --if-present

# Production image
FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

# Copy built application
COPY --from=builder /app ./

# Create non-root user
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nodeuser && \
    chown -R nodeuser:nodejs /app

USER nodeuser

EXPOSE {port}

CMD ["node", "dist/index.js"]
"#,
        port = port
    )
}

/// Generates a Dockerfile for NestJS applications.
fn generate_nestjs(port: u16) -> String {
    format!(
        r#"# NestJS Dockerfile
# Generated by Flaase

FROM node:20-alpine AS builder

WORKDIR /app

# Install dependencies
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN \
  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
  else npm install; \
  fi

# Copy source and build
COPY . .
RUN npm run build

# Production image
FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

# Copy package files and install production dependencies only
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN \
  if [ -f yarn.lock ]; then yarn --frozen-lockfile --production; \
  elif [ -f package-lock.json ]; then npm ci --only=production; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile --prod; \
  else npm install --only=production; \
  fi

# Copy built application
COPY --from=builder /app/dist ./dist

# Create non-root user
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nestuser && \
    chown -R nestuser:nodejs /app

USER nestuser

EXPOSE {port}

CMD ["node", "dist/main.js"]
"#,
        port = port
    )
}

/// Generates a Dockerfile for Laravel applications.
fn generate_laravel(port: u16) -> String {
    format!(
        r#"# Laravel Dockerfile
# Generated by Flaase

FROM php:8.3-fpm-alpine AS base

# Install system dependencies
RUN apk add --no-cache \
    git \
    curl \
    libpng-dev \
    libxml2-dev \
    zip \
    unzip \
    oniguruma-dev \
    postgresql-dev \
    nodejs \
    npm

# Install PHP extensions
RUN docker-php-ext-install pdo pdo_pgsql pdo_mysql mbstring exif pcntl bcmath gd

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Build stage
FROM base AS builder

WORKDIR /var/www

COPY composer.json composer.lock ./
RUN composer install --no-dev --no-scripts --no-autoloader

COPY . .
RUN composer dump-autoload --optimize

# Install npm dependencies and build assets
RUN if [ -f package.json ]; then npm ci && npm run build; fi

# Production image
FROM base AS runner

WORKDIR /var/www

# Copy application
COPY --from=builder /var/www ./

# Set permissions
RUN chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache

# Install Octane for high performance
RUN composer require laravel/octane --no-interaction || true
RUN php artisan octane:install --server=frankenphp || true

USER www-data

EXPOSE {port}

CMD ["php", "artisan", "octane:start", "--server=frankenphp", "--host=0.0.0.0", "--port={port}"]
"#,
        port = port
    )
}

/// Checks if a Dockerfile exists in the given directory.
pub fn exists(repo_dir: &std::path::Path) -> bool {
    repo_dir.join("Dockerfile").exists()
}

/// Returns the path to the Dockerfile in the repo.
pub fn path(repo_dir: &std::path::Path) -> std::path::PathBuf {
    repo_dir.join("Dockerfile")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_nextjs() {
        let dockerfile = generate(Stack::NextJs, 3000);
        assert!(dockerfile.contains("FROM node:20-alpine"));
        assert!(dockerfile.contains("EXPOSE 3000"));
        assert!(dockerfile.contains("Next.js"));
    }

    #[test]
    fn test_generate_laravel() {
        let dockerfile = generate(Stack::Laravel, 8000);
        assert!(dockerfile.contains("FROM php:8.3-fpm-alpine"));
        assert!(dockerfile.contains("EXPOSE 8000"));
        assert!(dockerfile.contains("Laravel"));
    }
}
